name: 'Spinnaker Compatibility Test Runner'
description: 'Action for running Spinnaker compatibility tests'
author: 'Armory'
inputs:
  service: 
    description: service to test
  version: 
    description: version to test
  skip_upload:
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
