name: 'Spinnaker Compatibility Test Runner'
description: 'Action for running Spinnaker compatibility tests'
author: 'Armory'
inputs:
  service: 
    description: service to test
  version: 
    description: version to test
  plugin_sha: 
    description: plugin commit to test
  skip_upload:
    default: false
  timeout_minutes:
    default: 10
    description: number of minutes to wait before timeout
runs:
  using: 'node12'
  main: 'dist/index.js'
